package ca.qc.ircm.proview.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.v7.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContactViewDesign extends VerticalLayout {
  protected VerticalLayout menuLayout;
  protected Label headerLabel;
  protected Panel proteomicContactPanel;
  protected Link proteomicContactNameLink;
  protected Link proteomicContactAddressLink;
  protected Link proteomicContactPhoneLink;
  protected Panel websiteContactPanel;
  protected Link websiteContactNameLink;
  protected Link websiteContactAddressLink;
  protected Link websiteContactPhoneLink;

  public ContactViewDesign() {
    Design.read(this);
  }
}
