package ca.qc.ircm.proview.web;

import ca.qc.ircm.proview.web.CustomLoginForm;
import ca.qc.ircm.proview.web.Menu;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainViewDesign extends VerticalLayout {
  protected Menu menu;
  protected Label header;
  protected CustomLoginForm signForm;
  protected Label forgotPasswordHeader;
  protected TextField forgotPasswordEmailField;
  protected Button forgotPasswordButton;
  protected Label registerHeader;
  protected Button registerButton;

  public MainViewDesign() {
    Design.read(this);
  }
}
