main:
  serverUrl: http://localhost:8080

spring:
  application:
    name: proview
  # Database.
  datasource:
    # MySQL database example.
    #     driver-class-name: com.mysql.jdbc.Driver
    #     url: jdbc:mysql://localhost/test
    #     username: dbuser
    #     password: dbpass
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;IGNORECASE=TRUE
    username: sa
    password:
    tomcat:
      test-on-borrow: true
      validationQuery: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      enabled: false
  thymeleaf:
    cache: false
  mail:
    host: myemailserver.com

# Web server.
server:
  servlet:
    session:
      persistent: false
  forward-headers-strategy: native
vaadin:
  productionMode: false
  closeIdleSessions: true

security:
  lockAttemps: 5
  lock-duration: PT3M
  disableSignAttemps: 20

ldap:
  enabled: false
  id-attribute: uid
  mail-attribute: mail

email:
  enabled: true
  from: proview@ircm.qc.ca
  to: christian.poitras@ircm.qc.ca
  subject: ${spring.application.name}

guidelines:
  home: ${user.dir}/guidelines
  categories:
    default:
      - name: 'Guidelines'
        guidelines:
          - name: 'Gel-free sample preparation'
            path: 'Guidelines_Gel-free_sample_preparation.doc'
      - name: 'Protocols'
        guidelines:
          - name: 'Gel staining protocols'
            path: 'Gel staining protocols.doc'
          - name: 'Immunoprecipitation Magnetic Dynabeads protocol'
            path: 'Immunoprecipitation Magnetic Dynabeads protocol.docx'
    fr:
      - name: 'Directives'
        guidelines:
          - name: 'Préparation des échantillons sans gel'
            path: 'Directives_de_préparation_des_échantillons_sans_gel.doc'
      - name: 'Protocoles'
        guidelines:
          - name: 'Protocoles coloration de gels'
            path: 'Protocoles coloration de gels.doc'
          - name: 'Protocole Immunoprecipitation Dynabeads'
            path: 'Protocole Immunoprecipitation Dynabeads.docx'

# Address to display by default on user registration page.
address:
  line: 110 avenue des Pins Ouest
  town: Montreal
  state: Quebec
  country: Canada
  postalCode: H2W 1R7

logging:
  file:
    name: ${spring.application.name}.log

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:file:./target/test-database;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE
  ldap:
    embedded:
      base-dn: dc=mycompany,dc=com
      credential:
        username: uid=poitrasc
        password: secret
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  mail:
    port: 30025
    host: localhost

security:
  rememberMeKey: 'JfYMi0qUQVt8FObsZHW7'
  passwords:
    - version: 1
      algorithm: SHA-256
      iterations: 1000

ldap:
  enabled: true
  object-class: person

logos:
  files:
    it: IRCM_horizontal_IT.png

guidelines:
  categories:
    it:
      - name: 'Linee guida'
        guidelines:
          - name: 'Preparazione del campione senza gel'
            path: 'Preparazione_del_campione_senza_gel.doc'
      - name: 'Protocolli'
        guidelines:
          - name: 'Protocolli di colorazione gel'
            path: 'Protocolli_di_colorazione_gel.doc'
          - name: 'Protocollo di immunoprecipitazione magnetica Dynabeads'
            path: 'Protocollo_di_immunoprecipitazione_magnetica_Dynabeads.docx'

logging:
  file:
    name: test.log

---
spring:
  config:
    activate:
      on-profile: integration-test
  datasource:
    url: jdbc:h2:file:./target/test-database;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

main:
  serverUrl: http://localhost:${local.server.port}

security:
  rememberMeKey: 'JfYMi0qUQVt8FObsZHW7'
  passwords:
    - version: 1
      algorithm: SHA-256
      iterations: 1000

email:
  enabled: false

guidelines:
  home: ${user.dir}/target/guidelines

logging:
  file:
    name: test.log

download-home: ${user.dir}/target/download

---
spring:
  config:
    activate:
      on-profile: context-path

server:
  servlet:
    context-path: /proview-test
