#
# Copyright (c) 2006 Institut de recherches cliniques de Montreal (IRCM)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

main:
  serverUrl: http://localhost

spring:
  application:
    name: proview
# Database.
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;IGNORECASE=TRUE
    username: sa
    password:
    tomcat:
      test-on-borrow: true
      validationQuery: SELECT 1
# MySQL database example.
#     driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://localhost/test
#     username: dbuser
#     password: dbpass
  http:
    multipart:
      enabled: false

# Web server.
server:
  session:
    persistent: false
vaadin:
  servlet:
    productionMode: false
    closeIdleSessions: true

security:
# Shiro.
  cipherKey: '0x2c9bff536d5bb8ae5550c93cdadace1b'
  passwords:
    - version: 1
      algorithm: SHA-256
      iterations: 1000
  maximumSignAttemps: 5
  maximumSignAttempsDelay: 300000  # 5 minutes.
  disableSignAttemps: 15
# Health.
  basic:
    path: /noUrlBecauseShiroSecurityIsUsedForVaadin
  user:
    name: admin

email:
  enabled: true
  host: myemailserver.com
  from: proview@ircm.qc.ca
  to: christian.poitras@ircm.qc.ca

# Address to display by default on user registration page.
address:
  address: 110 avenue des Pins Ouest
  town: Montreal
  state: Quebec
  country: Canada
  postalCode: H2W 1R7

logging:
  file: ${spring.application.name}.log

---
spring:
  profiles: test

logging:
  file: test.log

---
spring:
  profiles: integration-test

email:
  enabled: false
