package ca.qc.ircm.proview.treatment.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TreatmentViewDesign extends VerticalLayout {
  protected Label header;
  protected Label deleted;
  protected Panel protocolPanel;
  protected Label protocol;
  protected Panel fractionationTypePanel;
  protected Label fractionationType;
  protected Panel treatedSamplesPanel;
  protected Grid<ca.qc.ircm.proview.treatment.TreatedSample> treatedSamples;
  protected Panel explanationPanel;
  protected Label explanation;

  public TreatmentViewDesign() {
    Design.read(this);
  }
}
