/*
 * Copyright (c) 2006 Institut de recherches cliniques de Montreal (IRCM)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterDesign extends VerticalLayout {
  protected Label header;
  protected TextField email;
  protected TextField name;
  protected PasswordField password;
  protected PasswordField confirmPassword;
  protected Label laboratoryHeader;
  protected CheckBox newLaboratory;
  protected TextField organization;
  protected TextField laboratoryName;
  protected TextField managerEmail;
  protected Label addressHeader;
  protected TextField address;
  protected TextField addressSecond;
  protected TextField town;
  protected TextField state;
  protected ComboBox country;
  protected TextField postalCode;
  protected Button clear;
  protected Label phoneNumberHeader;
  protected TextField phoneNumber;
  protected TextField phoneExtension;
  protected Label registerHeader;
  protected Button register;
  protected Label required;

  public RegisterDesign() {
    Design.read(this);
  }
}
