package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterDesign extends VerticalLayout {
  protected Label header;
  protected TextField email;
  protected TextField name;
  protected PasswordField password;
  protected PasswordField confirmPassword;
  protected Label laboratoryHeader;
  protected CheckBox newLaboratory;
  protected TextField organization;
  protected TextField laboratoryName;
  protected TextField managerEmail;
  protected Label addressHeader;
  protected TextField address;
  protected TextField addressSecond;
  protected TextField town;
  protected TextField state;
  protected ComboBox country;
  protected TextField postalCode;
  protected Button clear;
  protected Label phoneNumberHeader;
  protected TextField phoneNumber;
  protected TextField phoneExtension;
  protected Label registerHeader;
  protected Button register;
  protected Label required;

  public RegisterDesign() {
    Design.read(this);
  }
}
