package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterDesign extends VerticalLayout {
  protected Label headerLabel;
  protected TextField emailField;
  protected TextField nameField;
  protected PasswordField passwordField;
  protected PasswordField confirmPasswordField;
  protected Label laboratoryHeaderLabel;
  protected CheckBox newLaboratoryField;
  protected TextField organizationField;
  protected TextField laboratoryNameField;
  protected TextField managerEmailField;
  protected Label addressHeaderLabel;
  protected TextField addressField;
  protected TextField addressSecondField;
  protected TextField townField;
  protected TextField stateField;
  protected ComboBox countryField;
  protected TextField postalCodeField;
  protected Button clearAddressButton;
  protected Label phoneNumberHeaderLabel;
  protected TextField phoneNumberField;
  protected TextField phoneExtensionField;
  protected Label registerHeaderLabel;
  protected Button registerButton;
  protected Label requiredLabel;

  public RegisterDesign() {
    Design.read(this);
  }
}
