package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RegisterViewDesign extends VerticalLayout {
  protected VerticalLayout menuLayout;
  protected Label headerLabel;
  protected Panel userPanel;
  protected VerticalLayout userFormLayout;
  protected Panel laboratoryPanel;
  protected CheckBox newLaboratoryField;
  protected TextField organizationField;
  protected TextField laboratoryNameField;
  protected TextField managerEmailField;
  protected Panel addressPanel;
  protected VerticalLayout addressFormLayout;
  protected Button clearAddressButton;
  protected Panel phoneNumberPanel;
  protected VerticalLayout phoneNumberFormLayout;
  protected Label registerHeaderLabel;
  protected Button registerButton;
  protected Label requiredLabel;

  public RegisterViewDesign() {
    Design.read(this);
  }
}
