package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.v7.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import com.vaadin.v7.ui.CheckBox;
import com.vaadin.v7.ui.ComboBox;
import com.vaadin.v7.ui.PasswordField;
import com.vaadin.v7.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView
 * extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class UserFormDesign extends VerticalLayout {
  protected Panel userPanel;
  protected TextField emailField;
  protected TextField nameField;
  protected PasswordField passwordField;
  protected PasswordField confirmPasswordField;
  protected Panel laboratoryPanel;
  protected CheckBox newLaboratoryField;
  protected TextField managerField;
  protected TextField organizationField;
  protected TextField laboratoryNameField;
  protected Panel addressPanel;
  protected TextField addressLineField;
  protected TextField townField;
  protected TextField stateField;
  protected TextField countryField;
  protected TextField postalCodeField;
  protected Button clearAddressButton;
  protected Panel phoneNumbersPanel;
  protected VerticalLayout phoneNumbersLayout;
  protected ComboBox phoneNumberTypeField;
  protected TextField numberField;
  protected TextField extensionField;
  protected Button removePhoneNumberButton;
  protected Button addPhoneNumberButton;
  protected VerticalLayout saveLayout;
  protected Label registerWarningLabel;
  protected Button saveButton;

  public UserFormDesign() {
    Design.read(this);
  }
}
