package ca.qc.ircm.proview.user.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewUserFormDesign extends VerticalLayout {
  protected Panel userPanel;
  protected VerticalLayout userFormLayout;
  protected Panel laboratoryPanel;
  protected VerticalLayout laboratoryFormLayout;
  protected Panel addressPanel;
  protected VerticalLayout addressFormLayout;
  protected Panel phoneNumbersPanel;
  protected VerticalLayout phoneNumbersLayout;
  protected Button addPhoneNumberButton;
  protected Button saveButton;
  protected Button cancelButton;

  public ViewUserFormDesign() {
    Design.read(this);
  }
}
