package ca.qc.ircm.proview.transfer.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TransferViewDesign extends VerticalLayout {
  protected VerticalLayout menuLayout;
  protected Label headerLabel;
  protected Label sourceHeaderLabel;
  protected TabSheet sourceTabs;
  protected Grid sourceTubesGrid;
  protected VerticalLayout sourcePlateLayout;
  protected ComboBox sourcePlatesField;
  protected Panel sourcePlatePanel;
  protected VerticalLayout sourcePlateFormLayout;
  protected Label destinationHeaderLabel;
  protected TabSheet destinationTabs;
  protected Grid destinationTubesGrid;
  protected VerticalLayout destinationPlateLayout;
  protected ComboBox destinationPlatesTypeField;
  protected ComboBox destinationPlatesField;
  protected Panel destinationPlatePanel;
  protected VerticalLayout destinationPlateFormLayout;

  public TransferViewDesign() {
    Design.read(this);
  }
}
