package ca.qc.ircm.proview.transfer.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TransferViewDesign extends VerticalLayout {
  protected Label headerLabel;
  protected Panel typePanel;
  protected RadioButtonGroup<ca.qc.ircm.proview.sample.SampleContainerType> type;
  protected Panel transfersPanel;
  protected Grid<ca.qc.ircm.proview.transfer.TransferedSample> transfers;
  protected Button down;
  protected Panel destination;
  protected VerticalLayout destinationPlateLayout;
  protected ComboBox<ca.qc.ircm.proview.plate.Plate> destinationPlatesField;
  protected Panel destinationPlatePanel;
  protected VerticalLayout destinationPlateFormLayout;
  protected Button test;
  protected Button save;

  public TransferViewDesign() {
    Design.read(this);
  }
}
