package ca.qc.ircm.proview.web.filter;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import org.vaadin.hene.popupbutton.PopupButton;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FilterInstantComponentDesign extends VerticalLayout {
  protected PopupButton filterButton;
  protected VerticalLayout popupLayout;
  protected InlineDateField fromDateField;
  protected InlineDateField toDateField;
  protected Button setButton;
  protected Button clearButton;

  public FilterInstantComponentDesign() {
    Design.read(this);
  }
}
