package ca.qc.ircm.proview.submission.web;

import ca.qc.ircm.proview.web.Menu;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EluateSubmissionViewDesign extends VerticalLayout {
  protected Menu menu;
  protected Label headerLabel;
  protected Label serviceLabel;
  protected Label informationLabel;
  protected Panel sampleCountPanel;
  protected TextField sampleCountField;
  protected Panel sampleNamesPanel;
  protected FormLayout sampleNamesForm;
  protected TextField sampleNameField;
  protected Button fillSampleNameButton;
  protected Panel experiencePanel;
  protected ComboBox projectField;
  protected TextField experienceField;
  protected TextField experienceGoalField;
  protected Panel sampleDetailsPanel;
  protected TextField taxonomyField;
  protected TextField proteinNameField;
  protected TextField proteinWeightField;
  protected TextField postTranslationModificationField;
  protected TextField sampleVolumeField;
  protected TextField sampleQuantityField;
  protected Panel standardsPanel;
  protected Panel contaminantsPanel;
  protected Panel digestionPanel;
  protected OptionGroup digestionOptions;
  protected Panel enrichmentPanel;
  protected Panel exclusionsPanel;
  protected Panel instrumentPanel;
  protected OptionGroup instrumentOptions;
  protected Panel proteinIdentificationPanel;
  protected OptionGroup proteinIdentificationOptions;
  protected Panel commentsPanel;
  protected TextArea commentsField;

  public EluateSubmissionViewDesign() {
    Design.read(this);
  }
}
