package ca.qc.ircm.proview.submission.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GelFormDesign extends VerticalLayout {
  protected ComboBox<ca.qc.ircm.proview.submission.GelSeparation> separation;
  protected ComboBox<ca.qc.ircm.proview.submission.GelThickness> thickness;
  protected ComboBox<ca.qc.ircm.proview.submission.GelColoration> coloration;
  protected TextField otherColoration;
  protected TextField developmentTime;
  protected CheckBox decoloration;
  protected TextField weightMarkerQuantity;
  protected TextField proteinQuantity;

  public GelFormDesign() {
    Design.read(this);
  }
}
