package ca.qc.ircm.proview.submission.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SubmissionTreatmentsFormDesign extends VerticalLayout {
  protected Panel samplesPanel;
  protected Grid<ca.qc.ircm.proview.sample.SubmissionSample> samples;
  protected Panel transfersPanel;
  protected Grid<ca.qc.ircm.proview.transfer.TransferedSample> transfers;
  protected Panel solubilisationsPanel;
  protected Grid<ca.qc.ircm.proview.solubilisation.SolubilisedSample> solubilisations;
  protected Panel digestionsPanel;
  protected Grid<ca.qc.ircm.proview.digestion.DigestedSample> digestions;
  protected Panel standardAdditionsPanel;
  protected Grid<ca.qc.ircm.proview.standard.AddedStandard> standardAdditions;
  protected Panel enrichmentsPanel;
  protected Grid<ca.qc.ircm.proview.enrichment.EnrichedSample> enrichments;
  protected Panel dilutionsPanel;
  protected Grid<ca.qc.ircm.proview.dilution.DilutedSample> dilutions;
  protected Panel fractionationsPanel;
  protected Grid<ca.qc.ircm.proview.fractionation.FractionationDetail> fractionations;

  public SubmissionTreatmentsFormDesign() {
    Design.read(this);
  }
}
