package ca.qc.ircm.proview.submission.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SubmissionHistoryFormDesign extends VerticalLayout {
  protected Panel samplesPanel;
  protected Grid<ca.qc.ircm.proview.sample.SubmissionSample> samples;
  protected Panel activitiesPanel;
  protected Grid<ca.qc.ircm.proview.history.Activity> activities;

  public SubmissionHistoryFormDesign() {
    Design.read(this);
  }
}
