ALTER TABLE samplecontainer
DROP FOREIGN KEY samplecontainer_sample_ibfk;
DROP TABLE IF EXISTS userpreference;
DROP TABLE IF EXISTS preference;
DROP TABLE IF EXISTS activityupdate;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS dataanalysis;
DROP TABLE IF EXISTS acquisition;
DROP TABLE IF EXISTS msanalysis;
DROP TABLE IF EXISTS treatedsample;
DROP TABLE IF EXISTS treatment;
DROP TABLE IF EXISTS protocol;
DROP TABLE IF EXISTS solvent;
DROP TABLE IF EXISTS standard;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS samplecontainer;
DROP TABLE IF EXISTS plate;
DROP TABLE IF EXISTS submissionfiles;
DROP TABLE IF EXISTS submission;
DROP TABLE IF EXISTS forgotpassword;
DROP TABLE IF EXISTS phonenumber;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS laboratory;
