package ca.qc.ircm.proview.sample.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContainerSelectionFormDesign extends VerticalLayout {
  protected Panel typePanel;
  protected RadioButtonGroup<ca.qc.ircm.proview.sample.SampleContainerType> type;
  protected Panel tubesPanel;
  protected Grid<ca.qc.ircm.proview.sample.Sample> tubes;
  protected Panel platesPanel;
  protected ComboBox<ca.qc.ircm.proview.plate.Plate> plates;
  protected Panel platePanel;
  protected VerticalLayout plateLayout;
  protected Button select;
  protected Button clear;

  public ContainerSelectionFormDesign() {
    Design.read(this);
  }
}
