package ca.qc.ircm.proview.sample.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SampleViewDesign extends VerticalLayout {
  protected Label header;
  protected Panel samplePanel;
  protected Label name;
  protected Label support;
  protected Label status;
  protected Label quantity;
  protected Label volume;
  protected Label numberProteins;
  protected Label molecularWeight;
  protected Panel containerPanel;
  protected Label containerType;
  protected Label containerName;
  protected Panel digestionsPanel;
  protected Panel enrichmentsPanel;
  protected Panel dilutionsPanel;
  protected Panel fractionationsPanel;
  protected Panel msAnalysesPanel;
  protected Panel dataAnalysesPanel;
  protected Button submission;
  protected Button history;

  public SampleViewDesign() {
    Design.read(this);
  }
}
