package ca.qc.ircm.proview.sample.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SampleFormDesign extends VerticalLayout {
  protected Panel samplePanel;
  protected Label name;
  protected Label support;
  protected Label status;
  protected Label quantity;
  protected Label volume;
  protected Label numberProteins;
  protected Label molecularWeight;
  protected Panel containerPanel;
  protected Label containerType;
  protected Label containerName;
  protected Panel digestionsPanel;
  protected Grid<ca.qc.ircm.proview.digestion.DigestedSample> digestions;
  protected Panel enrichmentsPanel;
  protected Grid<ca.qc.ircm.proview.enrichment.EnrichedSample> enrichments;
  protected Panel dilutionsPanel;
  protected Grid<ca.qc.ircm.proview.dilution.DilutedSample> dilutions;
  protected Panel fractionationsPanel;
  protected Grid<ca.qc.ircm.proview.fractionation.FractionationDetail> fractionations;
  protected Panel transfersPanel;
  protected Grid<ca.qc.ircm.proview.transfer.SampleTransfer> transfers;
  protected Panel msAnalysesPanel;
  protected Grid<ca.qc.ircm.proview.msanalysis.Acquisition> msAnalyses;
  protected Panel dataAnalysesPanel;
  protected Grid<ca.qc.ircm.proview.dataanalysis.DataAnalysis> dataAnalyses;

  public SampleFormDesign() {
    Design.read(this);
  }
}
