package ca.qc.ircm.proview.plate.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PlateViewDesign extends VerticalLayout {
  protected VerticalLayout menuLayout;
  protected VerticalLayout plateLayoutContainer;
  protected VerticalLayout newPlateLayoutContainer;
  protected VerticalLayout plateComponentContainer;
  protected Panel plateComponentPanel;

  public PlateViewDesign() {
    Design.read(this);
  }
}
