package ca.qc.ircm.proview.enrichment.web;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EnrichmentViewDesign extends VerticalLayout {
  protected Label header;
  protected Panel protocolPanel;
  protected ComboBox<ca.qc.ircm.proview.enrichment.EnrichmentProtocol> protocol;
  protected Panel enrichmentsPanel;
  protected Grid<ca.qc.ircm.proview.enrichment.EnrichedSample> enrichments;
  protected Button down;
  protected Button save;

  public EnrichmentViewDesign() {
    Design.read(this);
  }
}
